# Generated by Django 4.2.3 on 2023-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_system", "0002_alter_task_task_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_done_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
